function profopt = prefset(varargin)
%EBSET This function generates tracker options for Tracker,
% whose behaviour looks like optimset

profopt = struct("Language",              "Chinese", ...
                "ProgressBarVisible",     "on", ...
                "ProgressBarForeColor",   [0.30, 0.75, 0.93], ...
                "ProgressBarBackColor",   [0.90, 0.90, 0.90], ...
                "WindowStyle",            "classical", ...
                "CameraCache",            "memory", ...
                "IsParallelValid",        true, ...
                "CoresEnableCPU",         8, ...
                "IsGPUValid",             false, ...
                "CoresEnableGPU",         0, ...
                "TimeStampOpts",          struct("OffsetX",               EBScreenLayout.TIMESTAMP_OFFSET_X.Value, ...
                                                 "OffsetY",               EBScreenLayout.TIMESTAMP_OFFSET_Y.Value, ...
                                                 "HorizontalAligmnent",   "center", ...
                                                 "VerticalAlignment",     "top", ...
                                                 "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                 "FontColor",             [1, 1, 0]), ...
                "ScaleBarOpts",           struct("OffsetX",               EBScreenLayout.SCALE_OFFSET_X.Value, ...
                                                 "OffsetY",               EBScreenLayout.SCALE_OFFSET_Y.Value, ...
                                                 "HorizontalAligmnent",   "center", ...
                                                 "VerticalAlignment",     "bottom", ...
                                                 "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  14), ...
                                                 "FontColor",             [1, 1, 1]), ...
                "MetadataOpts",           struct("OffsetX",               EBScreenLayout.METADATA_OFFSET_X.Value, ...
                                                 "OffsetY",               EBScreenLayout.METADATA_OFFSET_Y.Value, ...
                                                 "HorizontalAligmnent",   "right", ...
                                                 "VerticalAlignment",     "bottom", ...
                                                 "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                 "FontColor",             [0, 1, 0]), ...
                "PlaySpeedOpts",          struct("OffsetX",               EBScreenLayout.SPEED_OFFSET_X.Value, ...
                                                 "OffsetY",               EBScreenLayout.SPEED_OFFSET_Y.Value, ...
                                                 "HorizontalAligmnent",   "center", ...
                                                 "VerticalAlignment",     "top", ...
                                                 "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                 "FontColor",             [1, 0, 0]), ...
                "DetectBoxOpts",          struct("HorizontalAligmnent",   "center", ...
                                                 "VerticalAlignment",     "top", ...
                                                 "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                 "FontColor",             "follow", ...
                                                 "BoxColor",              dictionary(["larva","bubble","impurities"],{[0,1,0],[1,0,0],[1,0,0]})), ...
                "TraceOpts",              struct("StayDuration",          10, ...
                                                 "Colormap",              "turbo", ...
                                                 "Transparency",          0.0));

end
