function dispopt = dispset(varargin)
%DISPSET This function generate VideoPlayer options for VideoPlayer,
% whose behaviour looks like optimset

% parse input
defaultImageOpt = struct("r",     [0, 4095], ...
                         "c",     1.0, ...
                         "b",     0, ...
                         "ga",    1.0, ...
                         "cmap",  "gray");

defaultMarkerOpts = struct("TimeStamp",    struct("OffsetX",               EBScreenLayout.TIMESTAMP_OFFSET_X.Value, ...
                                                  "OffsetY",               EBScreenLayout.TIMESTAMP_OFFSET_Y.Value, ...
                                                  "HorizontalAligmnent",   "center", ...
                                                  "VerticalAlignment",     "top", ...
                                                  "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                 "FontColor",             [1, 1, 0]), ...
                           "ScaleBar",     struct("OffsetX",               EBScreenLayout.SCALE_OFFSET_X.Value, ...
                                                  "OffsetY",               EBScreenLayout.SCALE_OFFSET_Y.Value, ...
                                                  "HorizontalAligmnent",   "center", ...
                                                  "VerticalAlignment",     "bottom", ...
                                                  "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  14), ...
                                                  "FontColor",             [1, 1, 1]), ...
                           "Metadata",     struct("OffsetX",               EBScreenLayout.METADATA_OFFSET_X.Value, ...
                                                  "OffsetY",               EBScreenLayout.METADATA_OFFSET_Y.Value, ...
                                                  "HorizontalAligmnent",   "right", ...
                                                  "VerticalAlignment",     "bottom", ...
                                                  "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                  "FontColor",             [0, 1, 0]), ...
                           "PlaySpeed",    struct("OffsetX",               EBScreenLayout.SPEED_OFFSET_X.Value, ...
                                                  "OffsetY",               EBScreenLayout.SPEED_OFFSET_Y.Value, ...
                                                  "HorizontalAligmnent",   "center", ...
                                                  "VerticalAlignment",     "top", ...
                                                  "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                  "FontColor",             [1, 0, 0]), ...
                           "DetectBox",    struct("HorizontalAligmnent",   "center", ...
                                                  "VerticalAlignment",     "top", ...
                                                  "Font",                  struct("FontName",  'Arial', ...
                                                                                 "FontWeight",'normal', ...
                                                                                 "FontAngle", 'normal', ...
                                                                                 "FontUnits", 'points', ...
                                                                                 "FontSize",  18), ...
                                                  "FontColor",             "follow", ...
                                                  "BoxColor",              dictionary(["larva","bubble","impurities"],{[0,1,0],[1,0,0],[1,0,0]})), ...
                           "Trace",        struct("StayDuration",          10, ...
                                                  "Colormap",              "turbo", ...
                                                  "Transparency",          0.0));
p = inputParser();

p.StructExpand = false;

addParameter(p, "Image", defaultImageOpt);
addParameter(p, "Marker", defaultMarkerOpts);

p.parse(varargin{:});

dispopt = struct("Image",   p.Results.Image, ...
                 "Marker",  p.Results.Marker);
end

