function expopt = exportset(varargin)
%EXPORTSET This function generate exporter options for MovieExporter,
% whose behaviour looks like optimset


expopt = struct("OutputFormat",     "Motion JPEG AVI", ...
                "OutputWidth",      1400, ...           % pixel
                "OutputHeight",     1000, ...           % pixel
                "OutputFrameRate",  25, ...
                "FrameRateSync",    true, ...
                "RenderingQuality", 75, ...
                "TargetMBitrate",   10, ...
                "Interpolation",    "bilinear", ...
                "OutputMarker",     "none", ...
                "Source",           "camera", ...
                "CompressionRatio", 2.0, ...
                "UseGrayscale",     false, ...
                "ExportStatus",     false);

end

