function trackopt = trackset(varargin)
%TRACKSET This function generate tracker options for Tracker,
% whose behaviour looks like optimset

trackopt = struct("lodopts", struct("classifier", "E:\si lab\Matlab Projects\EasyBehaviour\subapps\Tracker\utils\ObjectDetector\SVM\classifier_svm.bin", ...
                                    "alg",        "svm", ...
                                    "options",    struct("npobj",       [120, 30], ...
                                                         "robustness",  0.99, ...
                                                         "nobjmax",     30, ...
                                                         "object",      "larva")), ...
                  "mpopts",  struct("KFEnable",   false, ...
                                    "KFWin",      15), ...
                  "omopts",  struct("cost",       "Jaccard", ...
                                    "dist",       "Euclidean"), ...
                  "tkopts",  struct("mmdl",       MotionModel("Brownian-Gaussian"), ...
                                    "lambda",     0.88, ...
                                    "trcap",      8, ...
                                    "xRes",       0.1, ...
                                    "yRes",       0.1, ...
                                    "xLim",       [1, 2048], ...
                                    "yLim",       [1, 1088], ...
                                    "bxLim",      [15, 300]));

end
