function trackopt = trackset(varargin)
%TRACKSET This function generate tracker options for Tracker,
% whose behaviour looks like optimset

trackopt = struct("lodopts", struct("classifier", "E:\si lab\Matlab Projects\EasyBehaviour\subapps\Tracker\utils\ObjectDetector\SVM\classifier_svm.bin", ...
                                                      "alg",        "svm", ...
                                                      "options",    struct()), ...
                                    "mpopts",  struct("KFEnable",   false, ...
                                                      "KFWin",      9), ...
                                    "omopts",  struct("cost",       "Jaccard", ...
                                                      "dist",       "Euclidean"), ...
                                    "tkopts",  struct("target",     "larva", ...
                                                      "mmdl",       MotionModel("Brownian-Gaussian"), ...
                                                      "pth",        0.35, ...
                                                      "memlen",     10, ...
                                                      "xRes",       scale_option.xRes, ...
                                                      "yRes",       scale_option.yRes));

end

