function trackopt = trackset(varargin)
%TRACKSET This function generate tracker options for Tracker,
% whose behaviour looks like optimset

trackopt = struct("lodopts", struct("classifier", "E:\si lab\Matlab Projects\EasyBehaviour\subapps\Tracker\utils\ObjectDetector\SVM\classifier_svm.bin", ...
                                    "alg",        "svm", ...
                                    "options",    struct()), ...
                  "mpopts",  struct("KFEnable",   false, ...
                                    "KFWin",      15), ...
                  "omopts",  struct("cost",       "Jaccard", ...
                                    "dist",       "Euclidean"), ...
                  "tkopts",  struct("target",     "larva", ...
                                    "mmdl",       MotionModel("Brownian-Gaussian"), ...
                                    "pth",        0.5, ...
                                    "memlen",     10, ...
                                    "xRes",       0.1, ...
                                    "yRes",       0.1, ...
                                    "xLim",       [1, 2048], ...
                                    "yLim",       [1, 1088]));

end
