classdef EBVideoMarker
    %EBVIDEOMARKER 

    properties(GetAccess = public)
        Markers
    end
    
    methods
        function this = EBVideoMarker(withDetectBox, withMetadata, withPlaySpeed, withScaleBar,withTimeStamp, withTrajectory)
            %EBVIDEOMARKER 
            this.Markers = struct("DetectBox",      withDetectBox, ...
                                  "Metadata",       withMetadata, ...
                                  "PlaySpeed",      withPlaySpeed, ...
                                  "ScaleBar",       withScaleBar, ...
                                  "TimeStamp",      withTimeStamp, ...
                                  "Trajectory",     withTrajectory);
        end
    end

    methods(Static)
        function r = none()
            r = struct("DetectBox",     false, ...
                       "Metadata",      false, ...
                       "PlaySpeed",     false, ...
                       "ScaleBar",      false, ...
                       "TimeStamp",     false, ...
                       "Trajectory",    false);
        end

        function r = full()
            r = struct("DetectBox",     true, ...
                       "Metadata",      true, ...
                       "PlaySpeed",     true, ...
                       "ScaleBar",      true, ...
                       "TimeStamp",     true, ...
                       "Trajectory",    true);
        end
    end
end

