function scaleopt = scaleset(varargin)
%SCALESET This function generates scale options for ScaleBar,
% whose behaviour looks like optimset

scaleopt = struct("XRes",      0.1, ...
                  "YRes",      0.1, ...
                  "TimeUnit",  "s", ...
                  "ResUnit",   "mm", ...
                  "BarLength", 10);

end

